-- Elimina los tipo definidos

DROP TYPE tipo_ambiente_via_act3 FORCE;
DROP TYPE tipo_categoria_estado4 FORCE;
DROP TYPE tipo_servicio FORCE;
DROP TYPE tipo_etiqueta FORCE;
DROP TYPE IMAGEN_T FORCE;
DROP TYPE tipo_imagen FORCE;
DROP TYPE tipo_fecha_hora FORCE;
DROP TYPE COORDENADA_T FORCE;
DROP TYPE VIA_T FORCE;
DROP TYPE HITO_T FORCE;
DROP TYPE SERVICIO_T FORCE;
DROP TYPE PARADA_T FORCE;
DROP TYPE ACTIVIDAD_T FORCE;
DROP TYPE EVENTO_T FORCE;
DROP TYPE RUTA_T FORCE;
DROP TYPE GUIA_T FORCE;
DROP TYPE USUARIO_T FORCE;
DROP TYPE ELIGE_T FORCE;
DROP TYPE ORGANIZA_T FORCE;

-- Elimina los tipos definidos para referencias

DROP TYPE REF_VIAS_T FORCE;
DROP TYPE REF_RUTAS_T FORCE;
DROP TYPE REF_HITOS_T FORCE;
DROP TYPE REF_COORDENADAS_T FORCE;
DROP TYPE REF_ACTIVIDADES_T FORCE;


-- Elimina las tablas creadas (incluso la de las referencias anidadas)

DROP TABLE COORDENADA_GEOGRAFICA;
DROP TABLE VIA;
DROP TABLE PARADA;
DROP TABLE ACTIVIDAD;
DROP TABLE ELIGE;
DROP TABLE ORGANIZA;
DROP TABLE EVENTO;
DROP TABLE GUIA;
DROP TABLE USUARIO;
DROP TABLE RUTA;


